### ISSUE TITLE
loop Function - How to enable?

### ISSUE THREAD

**Issue by emitremmus** [georgepaterson/jquery-videobackground#10]
Hello,

can you please tell me where i can enable the loop function for the Video. I just readed on your Webside, that it is set default on FALSE. But where and how to enable?

Thanks.
emitremmus

**Comment by georgepaterson** [comment]
It can be set as an option when setting the video plugin:

$('.video-background').videobackground({
    videoSource: ['video/big-buck-bunny.mp4',
        'video/big-buck-bunny.webm', 
        'video/big-buck-bunny.ogv'],
    loop: 'true'
});
