### ISSUE TITLE
Ipad Support

### ISSUE THREAD

**Issue by Colin-Insivia** [georgepaterson/jquery-videobackground#11]
In both Ipad and Ipod touch devices, the video doesn't play (that's ok), but when it falls back, the background doesn't properly  stretch and you end up with a black bar to the left. In Ipod, I also had Z-Index issues in conjunction with this.

Test on:
IPad v1
IPod touch v4 (pretty sure)

I used detectmobilebrowsers.com to avoid the ipod / phone issues, but IPad isn't considered mobile by most detection scripts, so that one is still off.

**Comment by georgepaterson** [comment]
Hi, i don't personally have an iPad so i can't properly test but last time i looked the video would play in the background. Smaller devices like the iPhone and iPod require the video app to play video.

Do you have a URL for the video, if i can get access to an iPad i'll have a look.

**Comment by Colin-Insivia** [comment]
Thanks for getting back so promptly. I was able to reproduce the issue on the demo site.

**Comment by georgepaterson** [comment]
Ok will look in to it.

**Comment by georgepaterson** [comment]
Unfortunately iOS prevents video from loading in the background without an explicit user action. This is specific to iOS and goes against the default functionality of HTML5 autoplay attribute. iOS has closed out events that aren't triggered by a user, so autoplaying a video on iOS is not possible.
