### ISSUE TITLE
Type Attribute

### ISSUE THREAD

**Issue by Colin-Insivia** [georgepaterson/jquery-videobackground#12]
Hey George,

I noticed that the plugin doesn't add type attributes to the >source< tags. This causes browsers to download partial to full copies of the unneeded videos, in attempt to determine the mime type. I tested this in Firefox using the Firebug net panel.

I made a slight modification to the code, in order to utilize the passing of type. I suppose you could make this an optional format somehow, but based on the results, I would recommend requiring the video type be explicitly passed in the constructor. It will definitely cut down on requests for Firefox users, and probably all browsers.

Around line 39 of the JS.

```
$.each(element.settings.videoSource, function(index, value) { 
                      compiledSource = compiledSource + '<source src="' + value[0] + '" type="' + value[1] + '">';
```

The constructor:

```
videoSource: [['http://onecommunity.prod2.connectinsivia.com/wp-content/themes/onecommunity/_/vid/OneCommunity-Home-1.mp4', 'video/mp4'], ['http://onecommunity.prod2.connectinsivia.com/wp-content/themes/onecommunity/_/vid/OneCommunity-Home-1.webm', 'video/webm'], ['http://onecommunity.prod2.connectinsivia.com/wp-content/themes/onecommunity/_/vid/OneCommunity-Home-1.ogv', 'video/ogg']],
```

**Comment by georgepaterson** [comment]
It's a good idea, i'll implement it with a conditional for type.

**Comment by georgepaterson** [comment]
Master branch has been updated to include this and it'll be tagged as release 1.3. The tag also has a number of extra features like unit tests and data attribute support.
