### ISSUE TITLE
Loop/audio glitch

### ISSUE THREAD

**Issue by jrmypdgr** [georgepaterson/jquery-videobackground#13]
I enabled the loop function but when the video plays back the second time, the audio mutes, which is ok, I don't mind that. But when the video loops for the third time the audio switches back on. and it continues to switch on and off each loop cycle.

Anyone know how to fix that?

Thanks!

**Comment by georgepaterson** [comment]
Do you have a URL i can use as an example and the browser you're using? I can't at the moment replicate this.

**Comment by jrmypdgr** [comment]
I am trying to get it to upload now. But when I host the video it stops working all together

http://jaypeedesign.com/markrosas/

There's a link, let me know if anything pops out at you as to why it's not working!

Thank you so much!

**Comment by georgepaterson** [comment]
Looking at it in Chrome it works, not sure why it wouldn't work in Firefox as webm is supported. There is an empty source before and after the webm source, it may help to remove them.

Tangentially the video is almost 12Mb, this is a lot to download, i would recommend about 5Mb if you can reduce size without losing quality.

**Comment by georgepaterson** [comment]
Closing as it doesn't seem to be an issue with the plugin.
