### ISSUE TITLE
Redraw in Webkit

### ISSUE THREAD

**Issue by mmarquez** [georgepaterson/jquery-videobackground#14]
I don't know if it's solvable here.

I'm making a page using this plugin. In the page, a text is changed using intervals. In firefox it works great. But in webkit browsers, when the dom is changed the content is not refreshed.

**Comment by georgepaterson** [comment]
Do you have a URL to try this on?

**Comment by mmarquez** [comment]
I can't said the url yet. But I could only reproduce the issue in two computers with chrome in linux.

**Comment by georgepaterson** [comment]
Sorry chap i can't help until i've got something i can work with, open a new issue when you are able to share a URL and good luck.

**Comment by mmarquez** [comment]
Don't worry and thank you.

I've forked your code to add an event that is fired after the video has ended. If you think it can be useful ...
