### ISSUE TITLE
Will this work in iOS 6?

### ISSUE THREAD

**Issue by christiangenco** [georgepaterson/jquery-videobackground#15]
iOS 6 has some [new offerings for front end developers](http://news.ycombinator.com/item?id=4098857) - does anyone know if it will bring support for playing video in the background of a page?

**Comment by georgepaterson** [comment]
As i understand it, the iPhone will still play video in the video app, while iPad will play the video as a background.

**Comment by christiangenco** [comment]
Does the iPad support jquery-videobackground in iOS 5?

**Comment by georgepaterson** [comment]
It did when i last tested it. I don't have access to an iPad though.

**Comment by georgepaterson** [comment]
Unfortunately iOS prevents video from loading in the background without an explicit user action. This is specific to iOS and goes against the default functionality of HTML5 autoplay attribute. iOS has closed out events that aren't triggered by a user, so autoplaying a video on iOS is not possible.
