### ISSUE TITLE
destroy video after some time/at the end

### ISSUE THREAD

**Issue by johnalabama** [georgepaterson/jquery-videobackground#18]
Hi there, great plugin you've made!!
I'd only like to destroy the video after it's finished or after some time if not possible. I tried sleep(5); and setTimeout("$(this).videobackground('destroy')",5000); in the loaded callback, but nothing happens. Can you spare some hints?:)

**Comment by georgepaterson** [comment]
Hi John,

In the loaded callback you'll want to watch for the ended event on the video element, when triggered destroy the videobackground. Something the this:

var that = $(this); 
$(this).find('video').on('ended', function () {that.videobackground('destroy')});
