### ISSUE TITLE
Centerring video scalling

### ISSUE THREAD

**Issue by eduardokranz** [georgepaterson/jquery-videobackground#19]
Hi George,

I have been fiddling around with your plugin and I much appreciate that you made it open source.

I'm trying to keep the video centered when the width changes but the height doesn't. 
I'm currently adding a negative left margin to the video tag using the following code:

function resize(that) {
        var documentHeight = $(document).height(),
            windowHeight = $(window).height(),
            windowWidth = $(window).width();
        if (that.settings.resizeTo === 'window') {
            $(that).css('height', windowHeight);
// My code
            var videoBoxWidth = that.find('video').width(), difference, alignmentCorrection;
            if ( videoBoxWidth > windowWidth) {
                difference =  videoBoxWidth - windowWidth;
                alignmentCorrection = difference/2;
                $(that).find('video').css("margin-left", "-"+alignmentCorrection+"px");
            }
//End of my code
        } else {
            if (windowHeight >= documentHeight) {
                $(that).css('height', windowHeight);
            } else {
                $(that).css('height', documentHeight);
            }
        }
    }

As you can see I just appended my code to the resize function, however it doesn't trigger when the page first loads.
I'm considering to add it to the loadedCallback to trigger the align before the resize kicks in, then if the window resizes the resize function will take care of it. 

What do you think?

Regards,

Eduardo Kranz

**Comment by georgepaterson** [comment]
Hi Eduardo, sorry to have not responded earlier, either the loaded callback will be the right place to trigger an initial centering event.

Good luck,

George
