### ISSUE TITLE
No video in Safari 5.1

### ISSUE THREAD

**Issue by rokitDev** [georgepaterson/jquery-videobackground#2]
Hi George,

Fantastic plugin!   Works great in Firefox and Chrome.  It's not working in Safari Version 5.1 (6534.50) though.  Any ideas why not?

Thanks

**Comment by georgepaterson** [comment]
Bug reproduced. I'll try and find a fix.

**Comment by georgepaterson** [comment]
The problem was that i was calling a .m4v in the demo when it should have been a .mp4 which is supported in Safari. This issue should be fixed now.

**Comment by georgepaterson** [comment]
Issue confirmed fixed.
