### ISSUE TITLE
Chrome video loop fails and goes to black.

### ISSUE THREAD

**Issue by steven-king** [georgepaterson/jquery-videobackground#20]
We are having a problem in Chrome only where the video does not loop and goes to black. We have the parameter set to true in both the videobackground.js and in the function on the page. We see the same action on all pages on our site even with different videos.  Any ideas what might be causing this?

You can see it in action here:
http://reinhardt.jomc.unc.edu/
(video bg is about 30 seconds)

$('.video-background').videobackground({
                    videoSource: ['http://reinhardt.jomc.unc.edu/media/uploads/background-video/h264/fishes_noaudio_-_Computer.m4v',
                        'http://reinhardt.jomc.unc.edu/media/uploads/background-video/ogg/fishes_noaudio.ogv'], 
                    controlPosition: '.video-background',
                    poster: 'http://reinhardt.jomc.unc.edu/media/uploads/background-video/jpg/fish_bg.jpg',
                    loop: 'true', 
                    resize: 'true',
                    loadedCallback: function() {
                        $(this).videobackground('mute', {controlPosition: '.video-background'});
                    }
                });

BTW... thanks for providing the code for this. It works well and we are thankful!

Thanks,
Steven

**Comment by georgepaterson** [comment]
The code looks good and i'm not sure what the problem might be. You may want to try reducing the file size of the video. At 20Mb it may be causing unexpected problems with Chrome even if not 20Mb is a large file size, 5Mb would be more effective for your users. Try reducing the file size and i'll investigate further.

It's a great effect on the page though, nice work.

**Comment by steven-king** [comment]
Thanks George! We have been trying multiple encodes to get the best quality without sacrificing the experience. I will do a few tests at different sizes and reply to this thread with my findings. Thanks for the look, kind words and quick response!

**Comment by steven-king** [comment]
You are correct it was the size of the .ogv. 5mb works but are going to keep trying new encodes to see how far we can push it. Thanks!
