### ISSUE TITLE
iOS 6

### ISSUE THREAD

**Issue by Andy-Johnson** [georgepaterson/jquery-videobackground#21]
I love the speed and versatility of this code. It works in almost every browser I throw it at. Thanks for programming it.

One issue I’ve noticed is that on an iPhone, none of the internal href links within either your page 

http://www.georgepaterson.com/sandbox/jquery-html5-video-background-demo/

or mine

www.andrewdavidjohnson.com

None of the links on your page can be clicked on on an iPhone. I don’t think this is a wordpress thing as other wordpress sites allow ‘touchable’ links. Is it something to do with jquery incompatibility with iOS?

**Comment by phpfile** [comment]
I also noticed this on the IPhone4S.

**Comment by georgepaterson** [comment]
I don't seem to get this problem on an iPhone5 running iOS 6 with www.georgepaterson.com but i do see it on www.andrewdavidjohnson.com will investigate.

**Comment by georgepaterson** [comment]
It seems to be a CSS problem on your site Andy, i think it may be because of the use of position absolute, where i'm using position relative.
