### ISSUE TITLE
Poster image not resizing

### ISSUE THREAD

**Issue by wudges** [georgepaterson/jquery-videobackground#23]
Hi George,

First up, great plugin! Thanks very much for all the hard work that has no doubt gone into it.

I'm having issues with the poster image not resizing to fit the viewport in IE7 and 8, I've noticed the same in your demo. Is there a workaround or fix for it?

Thanks in advance.
Neil

**Comment by georgepaterson** [comment]
For now you could salvage the resize function and trigger when the poster image loads. 

What i've failed to do is build the loaded function to trigger when the poster is loaded rather than it just triggering when the video is loaded. I'll build that feature in to the next build.

**Comment by georgepaterson** [comment]
Just noticed a jQuery plugin called Backstretch come up, it may be better integrating that:

http://srobbin.com/jquery-plugins/backstretch/
