### ISSUE TITLE
IE9 Looping fails

### ISSUE THREAD

**Issue by mtlimon** [georgepaterson/jquery-videobackground#24]
Hi! I have tested videos on Firefox and Chrome and both browsers loop. On IE9 it does not. Goes to a faded white background. Any ideas?

**Comment by georgepaterson** [comment]
Do you have a URL i can look at? The demo site seems to run fine with Big Buck Bunny on IE9 but i could be missing something.

**Comment by mtlimon** [comment]
No live site just yet. Could I send you a video? I am trying to get a 360p or 480p to test out but I don't have it ready just yet to rule out file size as an issue.

**Comment by georgepaterson** [comment]
What's the file size of the video? If the video is quite large it can cause unexpected errors in the way the browser deals with playback.

**Comment by mtlimon** [comment]
13MB?

**Comment by georgepaterson** [comment]
Check out issue #20 Steven had a similar issue in Chrome.

I'm not sure of the reason why, i'd like to spend time to investigate but it's possible larger files size cause the video loop to fail. It could be that the video fails to download before the loop is triggered. So the length of the video could also be a factor.

Reducing to around 5Mb will help, you can then trial different quality versus file size ratios to get your desired effect.

**Comment by mtlimon** [comment]
Thank you. I changed to video out with a 480p and 360p and sure enough, it works.
