### ISSUE TITLE
Stopped working on Chrome

### ISSUE THREAD

**Issue by Howman** [georgepaterson/jquery-videobackground#25]
jquery-videobackground has stopped working on chrome 23. it also does not work on your demo page with chrome version 23

**Comment by georgepaterson** [comment]
Can't replicate in OSX Chrome Version 23.0.1271.97.

**Comment by Howman** [comment]
I just updated to Version 23.0.1271.97 m and it will play about 15 sec then screen goes all white I am using windows 8 pro

**Comment by georgepaterson** [comment]
Just had a look in Windows 8 on Chrome as well and can't replicate. You have a crash report or similar to work with?

**Comment by Howman** [comment]
well I am just using chrome and going to your site http://georgepaterson.github.com/jquery-videobackground/ and any where between 3 and 15 sec the video will go white.
using chromes developer tools network 
headers
Request URL:http://georgepaterson.github.com/jquery-videobackground/video/big-buck-bunny.mp4
Request Method:GET
Status Code:206 Partial Content (from cache)
big-buck-bunny.mp4
/jquery-videobackground/video
GET
(canceled)
application/octet-stream
georgepaterson.github.com:153
Parser
(from cache)
437ms
12ms

Where would I look for a crash report
Is some where i could go to get Info you would need

**Comment by Howman** [comment]
This Is from My Sites IIS 8 Log
2012-12-13 17:39:48 192.168.2.16 GET /myaddons/videobackground/video/Video-Loops-Motion-Backgrounds.mp4 - 80 - 192.168.2.16 Mozilla/5.0+(Windows+NT+6.2;+WOW64)+AppleWebKit/537.11+(KHTML,+like+Gecko)+Chrome/23.0.1271.97+Safari/537.11 http://www.howman.ca/ 206 0 995 6941
this Is on a local host So if you went to howman.ca you would not see the video cause i have not made it live. site being tested on my laptop so I have not put it over to my sever pc yet.

**Comment by georgepaterson** [comment]
Sorrt Howman but i can't replicate or find the source of the problem. It's possible code on your existing site is conflictng with the video background.
