### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by albertidimentico** [georgepaterson/jquery-videobackground#26]
My problem is related to the loop. In the. Js is true and the script.
But it does not work, please show me an example.

Many Thanks, Greetings

$(document).ready(function() {
                $('dl').toggle();
                $('h2').bind('click', function(event) {
                    event.preventDefault();
                    $(this).next('dl').slideToggle(500, function() {
                        $('.video-background').videobackground('resize');
                    });
                });
                $('body').prepend('<div class="video-background"></div>');
                $('.video-background').videobackground({
                    videoSource: [['video/big-buck-bunny.mp4', 'video/mp4'],
                        ['video/big-buck-bunny.webm', 'video/webm'], 
                        ['video/big-buck-bunny.ogv', 'video/ogg']], 
                    controlPosition: '#main',
                    poster: 'video/big-buck-bunny.jpg',
                                        loop;true,
                    loadedCallback: function() {
                        $(this).videobackground('mute');

```
                }
            });
        });
```

</script>

**Comment by georgepaterson** [comment]
Looks like you have a semicolon when you need a colon:

loop; true,

loop: true,

**Comment by albertidimentico** [comment]
Hello thank you very much that this, if I had that error and true change in js file but still not working the loop. If you can help, thank you very much

```
        $(document).ready(function() {
            $('dl').toggle();
            $('h2').bind('click', function(event) {
                event.preventDefault();
                $(this).next('dl').slideToggle(500, function() {
                    $('.video-background').videobackground('resize');
                });
            });
            $('body').prepend('<div id="todo"><div class="video-background"></div>');
            $('.video-background').videobackground({

                videoSource: [['video/big-buck-bunny.mp4', 'video/mp4'],
                    ['video/big-buck-bunny.webm', 'video/webm'], 
                    ['video/big-buck-bunny.ogv', 'video/ogg']], 


                loop:true,
                controlPosition: '#main',
                poster: 'video/big-buck-bunny.jpg',

            });
```

});

**Comment by albertidimentico** [comment]
Muchas gracias por todo ya e conseguido hacer funcionar el loop. Repito muchas gracias por su tiempo.
