### ISSUE TITLE
Best way to pull poster in iPad/iPhone

### ISSUE THREAD

**Issue by aa-utsoa** [georgepaterson/jquery-videobackground#27]
Hi, this is working beautifully — thank you!

Trying to degrade gracefully on iPhones & iPads, how would you recommend I turn off video background? 

Here's my prototype:
http://bit.ly/UuKZ4u

Thanks!

**Comment by aa-utsoa** [comment]
Sorry, located here: http://bit.ly/V2Hn8r

**Comment by georgepaterson** [comment]
Normally i say feature detection but the feature you want exists, it's just Apple have decided to change it's interaction. That leaves user agent detection. You can try navigator.userAgent to determine if you have an iOS device and not trigger the videobackground if so.

**Comment by georgepaterson** [comment]
Leaving it open if you have a further query.

**Comment by aa-utsoa** [comment]
No, got it, thanks.
