### ISSUE TITLE
Help loop 

### ISSUE THREAD

**Issue by albertidimentico** [georgepaterson/jquery-videobackground#28]
Hi sorry for taking another look but I still can not find the problem and solution in js is true and the script. But that is not the problem. many Thanks

$(document).ready(function() {
                $('dl').toggle();
                $('h2').bind('click', function(event) {
                    event.preventDefault();
                    $(this).next('dl').slideToggle(500, function() {
                        $('.video-background').videobackground('resize');
                    });
                });
                $('body').prepend('<div id="todo"><div class="video-background"></div>');
                $('.video-background').videobackground({

```
                videoSource: [['video/big-buck-bunny.mp4', 'video/mp4'],
                    ['video/big-buck-bunny.webm', 'video/webm'], 
                    ['video/big-buck-bunny.ogv', 'video/ogg']], 



                controlPosition: '#main',
                poster: 'video/big-buck-bunny.jpg',
            loop:'true',
                loadedCallback: function() {
                $(this).videobackground('mute');
                            }

            });
```

**Comment by georgepaterson** [comment]
The video code looks like it should work, what browser are you using, do you have a demo to view?
