### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by mtlimon** [georgepaterson/jquery-videobackground#29]
Hi George, 

I've test the video background on the iPad (2nd Gen) and the Safari browser for the PC, but it only shows the poster image. I used the iPad's Chrome and Safari Browser. Any ideas? Works on the desktop PC's though, Firefox, IE9, and Chrome.

I tried your demo page and sure enough, it was the poster image.

Thanks in advance for your help.

**Comment by georgepaterson** [comment]
Hi, 

Apple by default blocks video automatically playing on iOS, it's to protect the users battery life. Unfortunately there isn't a way around this as Apple has closed down any loop holes.

Safari works for me on Windows 8 (Safari 5.1.7) and Mac (Safari 6.0). Interesting to see there's no Windows update for Safari.

**Comment by mtlimon** [comment]
Thanks for the info George! I'll create a video embed elsewhere on the page.

Maria T. Limon

**Comment by georgepaterson** [comment]
iOS 6.0.1 seems to have brought video back and it doesn't scale...

For issue #30 i've considered just bailing on iOS as it's an inconsistent experience.
