### ISSUE TITLE
Firefox & resize issue

### ISSUE THREAD

**Issue by eddyfever** [georgepaterson/jquery-videobackground#3]
He George, 

I wanna to use your code for a project, so far it works but have a few problems or maybe bugs.

(Tested on a mac)
- The video doesn't show up at all in firefox, your test files works fine.
- The resize function doesn't same to regonize my video, with yes or true or what so ever.

Hope you can help me with this. Thank you already for your time.

example url: http://mucc.nl/clients/rietveld/index.php/

This is the code i use (ignore {site_url}, and the video is your bunny video but i renamed them as test (ogg en webm):

<script type="text/javascript" src="{site_url}ontwerp/scripts/jquery.videobackground.js"></script>  

```
<script>
        $(document).ready(function() {

            $('body').prepend('<div class="video-background"></div>');
            $('.video-background').videobackground({
                videoSource: [
                    '{site_url}ontwerp/scripts/assets/rietveld1.mp4', 
                    '{site_url}ontwerp/scripts/assets/rietveld1.webm', 
                    '{site_url}ontwerp/scripts/assets/rietveld1.ogv'], 
                controlPosition: '#main',
                loop: 'yes',
                resize: 'yes',
                loadedCallback: function() {
                    $(this).videobackground('mute', {controlPosition: '#main'});
                }
            });
        });
    </script>
```

CSS:
.video-background{
z-index: -999;
position: absolute;
width: 100%;
height: 100%
min-height: 100%
background: #b3b3b5;
}

**Comment by georgepaterson** [comment]
Hi,

For the issue of the video not playing, the web server for your site needs the video mime types added. Not sure what it is for IIS but for Apache you'd add these to httpd.conf:

AddType video/webm .webm
AddType video/ogg .ogv
AddType video/mp4 .mp4

The video should then be able to play directly in the browser like this:

http://www.georgepaterson.com/wp-content/uploads/jquery/jquery-videobackground/video/big-buck-bunny.ogv

Where your video currently cannot:

http://mucc.nl/clients/rietveld/ontwerp/scripts/assets/rietveld1.ogv

For the second issue loop and resize should use true or false values:

loop: true,
resize: true,

By default resize is set to true while loop is set to false, so you only need to set the loop parameter in your script.

This should resolve both issues.

**Comment by eddyfever** [comment]
Thank you for your fast reply.
I'm totally new with the some of these video formats so i didn't know it has something to do with the server.
I'll contact my hosting provider about that issue.

About the resize option i'm still stuck. I removed the resize parameter, but with no success.
Are there any more things i have to think about?
I think my CSS is correct, are can i be the video it self?

Again thank you for your time.

**Comment by eddyfever** [comment]
Got it!

Forgot:

```
.video-background video {
            min-height: 100%; 
            min-width:100%; 
        } 
```

**Comment by georgepaterson** [comment]
Excellent.

**Comment by eddyfever** [comment]
one more little question.

I use now autopay: 'false', that works great, but is it possible to show then the poster as default?
Because i use a still screen from frame1 of the movie and i wanna let users choose to play the video yes or no.

Thank you again and already for your time. 

Extra info: 
I wanna have two background images.
1. For people who can watch the video - Frame 1 of the video
2. Custom background for non video browsers, this i fixed with backstretch.js

So thats why i hoped the poster could fill in the background for Video-browsers

**Comment by georgepaterson** [comment]
For the first question i think you'll need to use the preload and loaded callbacks. As part of your plugin settings you can use these callbacks to trigger additional JavaScript. Have a look at http://www.georgepaterson.com/2011/06/13/jquery-html5-video-background-1-0-0/#comment-656 for the loadedCallback parameter.

I built something similar where the user can skip the video before the loaded event but it is awaiting release.

Two posters might be tricky for the plugin itself but you could use the below code to preemptively distinguish between those that support video and those that don't.

if (document.createElement('video').canPlayType) {
  $('.video-background').videobackground()
}
else {
  // Second poster image using backstretch.js code.
}
