### ISSUE TITLE
clicking troubles on iPhone

### ISSUE THREAD

**Issue by ghost** [georgepaterson/jquery-videobackground#30]
Dear George, this plug is amazing and very easy to implement – even for me as a non jquery developer. So thank you very much for your work on this George, it helped me a lot, really.

But I think there is a bug:

On my iphone 3GS with iOS 4, while testing your demo site http://georgepaterson.github.com/jquery-videobackground/, everything looks ok: the poster image is displayed, because this device doesn't support the HTML5 video background. But while I can see the contents of the page floating over the poster image correctly, I'm not able to click on any of the links. As if there is an invisible layer between the page and my finger, that stops me from clicking on anything.

Do you know what could cause this behaviour? Is there a fix for that?

Thank you very much and best regards,

Tom

**Comment by georgepaterson** [comment]
The way iOS works with video makes a video background tricky and Apple have at times blocked video from working. For instance now on iOS 6.0.1 video works and drops the user in to the video player when ready on iPhone. On iPad it's not scaling the video but at least it doesn't drop you in to the video player.

The specific issue of links not working on an iPhone seem to be the way the iPhone creates the video by cutting a hole for a Quicktime video in the page, underneath the hole are the links, making them non-clickable. 

There isn't a consistent fix so I would avoid triggering the video background on an iPhone, perhaps even iOS, i can't feature detect consistently so it may require you to do a user agent test before running the plugin.

if (navigator.userAgent.match(/(iPod|iPhone|iPad)/)) {
    // Set a CSS background.
} else {
    $('.your-video').videobackground();
}

It's not elegant but it'll work.

**Comment by ghost** [comment]
Thanks for your kind explanation. I'll give it a try, it seems to be a reasonable solution.

Apple is the new Microsoft, huh? :-)
