### ISSUE TITLE
loading video with firefox

### ISSUE THREAD

**Issue by roberta79** [georgepaterson/jquery-videobackground#31]
hi, I'm sorry for my english ... but I have a problem with the plugin and I hope you can help me.
I do not know if I can write in this space to communicate my problem.
I would like to use your plugin for my site and do tests. this is the link test: http://www.gabrielepici.com/jquery-videobackground-master/jquery-videobackground-master/index.html
I renamed my video with the same name as your example (big-buck-bunny). With explorer and chrome I see my new video but with firefox i still see the video big-buck-bunny. why?
What's wrong?
I hope you can help me and I congratulate you for this great plugin

**Comment by georgepaterson** [comment]
There are 3 video formats referenced by the script. You've updated the .mp4 video:

http://www.gabrielepici.com/jquery-videobackground-master/jquery-videobackground-master/video/big-buck-bunny.mp4

But Firefox doesn't use .mp4 (http://caniuse.com/mpeg4) so you'll need to update the .webm file:

http://www.gabrielepici.com/jquery-videobackground-master/jquery-videobackground-master/video/big-buck-bunny.webm

You should be able to remove the .ogv reference.

**Comment by roberta79** [comment]
I see ... I did not know this little problem. thank you very much and congratulations for your plugin
