### ISSUE TITLE
Video doesn't display correctly in Safari

### ISSUE THREAD

**Issue by krstnz** [georgepaterson/jquery-videobackground#33]
Hi George!

Thanks for the great template! It works well on all browsers except for Safari, where the video show up really small in the left top corner for some reason. I noticed that someone mentioned this issue earlier and that it had something to do with calling for the wrong file extension, but that it was fixed. Any idea why it doesn't work in Safari again? I would really appreciate your help!!
Thanks so much for making this open source!!

**Comment by georgepaterson** [comment]
Do you have a link to try? The demo site with Safari 6.0 on OSX seems to work ok. If you are getting a video to load, even if it's small, it's not a video extension problem but a CSS problem. Check out the styling in the demo but you'll need absolute positioning, with an initial min-height and min-width to start with.

I changed to a Github page recently so it's here is you want to review the demo in Safari:
http://georgepaterson.github.com/jquery-videobackground/

**Comment by georgepaterson** [comment]
If you're still having problems then feel free to reopen the ticket.
