### ISSUE TITLE
Video does not work on server. Locally, all it's write...

### ISSUE THREAD

**Issue by Akrosid** [georgepaterson/jquery-videobackground#34]
I downloaded and unzip the zip. I did not change anything.With firefox, As I open it locally: it works. But when I put the files on the server, the video does not work. But for safari work.

If you want tchek that:
http://zeckart.com/testvideo1/

sorry for my bad english

**Comment by georgepaterson** [comment]
You'll need to update the server mime types for the video types you're using. It should then play the video directly in the browser rather than making it a downloadable file.

**Comment by Akrosid** [comment]
Thank you but what I need to change in the htaccess file? 

Just add that?:

AddType video/x-mp4 .mp4
AddType video/x-ogv .ogv
AddType video/x-webm .webm

**Comment by Akrosid** [comment]
Ok I solve my problem !!

Just add that to .htaccess:

AddType video/ogg .ogv
AddType video/webm .webm
AddType video/mp4v-es .mp4
AddType audio/mp4 .mp4
