### ISSUE TITLE
Add a proper semver tag

### ISSUE THREAD

**Issue by satazor** [georgepaterson/jquery-videobackground#35]
Hi! I'm André, a core member of [bower](http://github.com/twitter/bower). Can you please make the v1.3 a valid semver tag? (v.1.3.0). Thanks.

**Comment by georgepaterson** [comment]
Add a v1.3.1 tag. Does that work?

**Comment by satazor** [comment]
Yes! Thanks!

**Comment by georgepaterson** [comment]
Cool
