### ISSUE TITLE
video background plays for 3 seconds in chrome and it becomes white.

### ISSUE THREAD

**Issue by raies** [georgepaterson/jquery-videobackground#36]
Hi,
The video background works perfect in firefox and even internet explorer.
But it does not work for me in chrome.

the video plays for a few seconds and the background becomes white.

I have it uploaded to test at www.test.kungfucasting.com

thank you very much for the help.

kind regards,

raies

**Comment by alanmarcos** [comment]
Switch the order of the video files. Put the .webm first in the code so chrome will try to open it first.

**Comment by georgepaterson** [comment]
Do you have an event bound to the page? After clicking the page the video shows over the white background. It looks like it's to do with the 'Enter' link and the video is waiting for an event associated with it.

**Comment by rabelais** [comment]
I have the same problem here http://kimcolemanprojects.com/index.html 
The screen is white until user clicks. I can't work out why. I have no event bound to the page as far as I can see. Any advice? Thanks

**Comment by georgepaterson** [comment]
Vidao looks fine in Chrome on a Mac rabelais, have you tried something since the comment?

**Comment by rabelais** [comment]
Yes, I put this script in at the end on my page and it seems to have stopped the page waiting for a click event. It was a problem on chrome on other computers as well not just mac. 

<script>
  $(document).ready(function() {
    setTimeout(function() {
      document.getElementsByTagName('video')[0].style.display = '';
    }, 500);
  });
</script>

**Comment by georgepaterson** [comment]
Ah i see, well if it works that's cool.
