### ISSUE TITLE
I can't get the plug-in to function in Firefox and don't understand why..

### ISSUE THREAD

**Issue by mcsam90** [georgepaterson/jquery-videobackground#37]
Hi there,

I'm simply trying to have a fullscreen video that fits the browser window and automatically plays when the page loads, so this plug-in has been great for that and I'm really appreciative. However, I can't understand why I can't get it to function in Firefox and I'm hoping someone can point out an obvious reason as to why it isn't working. 

Webpage is: http://palmsofpalms.com/

Also, a secondary problem is a little jump as it loads on other browsers. Is that due to a problem with my poster image? Is 25mb too large for the video file?

Thanks a lot

Sam

**Comment by kwhc** [comment]
Even though Firefox 4+, Opera 10.6+ and Chrome 6+ support WebM, FF didn't appear to be loading my mp4 or WebM file. Once I created an .ogg version of it, it loaded just fine.

Seems like you just need to provide as much to fall back on as possible.

**Comment by georgepaterson** [comment]
You do need to cover the bases but i think the 25 Mb file may not be helping. Around 5 Mb seems to work best as the browser seems to have problems with automatically playing large looping files.
