### ISSUE TITLE
Request: Video Play Method

### ISSUE THREAD

**Issue by kwhc** [georgepaterson/jquery-videobackground#38]
I would love a method to trigger something each time the video plays when on a loop. Essentially I'd like to build out a counter from that being triggered each time.

**Comment by georgepaterson** [comment]
Yeah i'll try and add another callback if possible.

**Comment by georgepaterson** [comment]
So i decided to leverage the existing loadedCallback rather than creating a new call back:

loadedCallback: function() {
    this.find('video').on('ended', function () {
        // Your video end event.
    });
}

The call back will listen for the ended event of the video in the video background and trigger the code you need. Haven't fully tested but it should work.

**Comment by georgepaterson** [comment]
If you still have a problem feel free to open an issue.
