### ISSUE TITLE
Firefox and Video

### ISSUE THREAD

**Issue by Clomascara** [georgepaterson/jquery-videobackground#39]
Hi,
thanks for the great plugin.
I have two questions:
- I have problems with playing the video in IE and FF. If I try to run it locally it works, but if I try to www in FF is only the cover. It's caused by the configuration of the file httpd.config?
- I activated the loop, but I would like to find a solution to make  that at the end of a video it starts a new one. is it possible?

thanks
Have a nice day

**Comment by georgepaterson** [comment]
For the first problem you need to add the video type to the server check out the answer to issue #34

You may be able to code an extension but the plugin currently doesn't support loading a new video after the first loads. I'm a bit time poor at the moment so would have to see if i can make a change at a later date.

**Comment by georgepaterson** [comment]
Have a look at the solution to issue #38 that should help you.
