### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by logixstudios** [georgepaterson/jquery-videobackground#4]
I can't seem to play a video on an iOS device.

**Comment by georgepaterson** [comment]
Which device are you using? 

It should work on iPad but the iPhone/iTouch uses a dedicated video player which makes a video background impossible.

**Comment by logixstudios** [comment]
That explains it, thanks! I was trying to use it on an iPhone.

**Comment by georgepaterson** [comment]
Cool.
