### ISSUE TITLE
jquery-videobackground Not Working In IE 10

### ISSUE THREAD

**Issue by Howman** [georgepaterson/jquery-videobackground#41]
O.K.
I am on windows 8 And using IE 10.0.9200.16580 and the script does not work. But will work with chrome and fire fox I have tried two other computers and same thing only IE 10 so I tried your demo site and your demo will not work for me.
But it did work In IE I think my windows took a update and that's when it broke.

Could you check for me with your computer I remember asking you something like this before but for chrome and the next chrome update fixed it.

But IE does not update like chrome or firefox does I know Windows 8.1 will have IE 11 but can not get IE 11 till june 26 to test

**Comment by georgepaterson** [comment]
Replicated on my machine, can't see an obvious reason. Will need to investigate.

**Comment by Howman** [comment]
206 http error and it did work before  MS13-037: Cumulative Security Update for Internet Explorer: May 14, 2013 cause i remember setting the script up on my localhost

**Comment by Howman** [comment]
Sorry Pressed wrong button did not mean to close

**Comment by Howman** [comment]
Did you get a chance to look in to a fix for this yet?

**Comment by georgepaterson** [comment]
Sorry been busy at work and haven't found the issue yet.

**Comment by georgepaterson** [comment]
First proper look at it, the video doesn't work on the server but will work locally on IE10 and passes all test. It may be a server issue, will look for other examples.

**Comment by georgepaterson** [comment]
Issue #42 has it working in IE10, definitely looks to be a server issue.

**Comment by Howman** [comment]
I tried http://localgear.com/ on my IE 10 and it does not work but does in firefox and chrome
I will try Ie 10 developer tools and the network. I will post what it says

**Comment by Howman** [comment]
Key                    Value
Response                       HTTP/1.1 206 Partial Content
x-amz-id-2                     PJpwH4kKaKLeKoHXCRSSwQx2qm6OWeMEyMmmgFBH+Y1FRyb1b7L8S0GmrOy9P3wD
x-amz-request-id    1B64F1A7966EFE5B
Date                      Thu, 20 Jun 2013 17:29:19 GMT
Last-Modified   Tue, 11 Jun 2013 17:14:23 GMT
ETag                     "28c0b1aa61d11aff3dd7d953eddbb821"
Accept-Ranges   bytes
Content-Range   bytes 49152-653710/653711
Content-Type    video/mp4
Content-Length  604559
Server                   AmazonS3

**Comment by Howman** [comment]
This is from your demo site
Key Value
Response    HTTP/1.1 206 Partial Content
Server  GitHub.com
Content-Type    application/octet-stream
Last-Modified   Sun, 18 Nov 2012 17:08:25 GMT
Expires Thu, 20 Jun 2013 17:42:37 GMT
Cache-Control   max-age=600
Accept-Ranges   bytes
Date    Thu, 20 Jun 2013 17:33:19 GMT
Via 1.1 varnish
Age 41
Connection  keep-alive
X-Served-By cache-d46-DAL
X-Cache HIT
X-Cache-Hits    1
X-Timer S1371749599.253507614,VS0,VE0
Vary    Accept-Encoding
Content-Range   bytes 0-5510871/5510872
Content-Length  5510872

**Comment by georgepaterson** [comment]
The localgear.com site works i believe because it has the correct content type set:

Content-Type video/mp4

The Github demo site doesn't work because it's content type is not properly define:

Content-Type application/octet-stream

Will have to look at putting a .htaccess one the Github site to set the correct content type. This is the reason for the video not playing, although i'm not sure why it doesn't work in your IE10. Perhaps have you checked the developer tools to make sure you've not dropped in to compatibility mode?

**Comment by Howman** [comment]
No I am not in compatibility mode I am going to check my windows server 2012 and see what it does there

**Comment by Howman** [comment]
localgear.com does work on my windows server 2012 IE 10.0.6
it shows GET 304 and nothing for content type
localgear.com on this computer does not work (windows 8) IE 10.0.6
it shows GET 206 video/mp4 for content type
Could this be a cache problem with my windows 8
