### ISSUE TITLE
Video not working in safari

### ISSUE THREAD

**Issue by jrdn91** [georgepaterson/jquery-videobackground#42]
The video is not being added at all in safari

**Comment by georgepaterson** [comment]
Do you have a URL i can look at?

**Comment by phirschybar** [comment]
demo doesn't work in safari. otherwise seems to work well (other browsers).

**Comment by phirschybar** [comment]
also here is a URL where it does not work in safari: http://localgear.com/

**Comment by georgepaterson** [comment]
Yeah not sure why Safari has dropped again, will look when i get a chance. Thanks for the URl.

**Comment by phirschybar** [comment]
thanks a lot george. great plugin. seems like other video solutions are also struggling with safari.

**Comment by georgepaterson** [comment]
Yeah there seems to be arbitrary changes between releases, as i understand it, it's because Safari is used on iOS and has different requirements to a desktop browser.

**Comment by georgepaterson** [comment]
Looks like it's working at the URL http://localgear.com/ now. May have been a minor release issue with Safari. Nice design phirschybar.
