### ISSUE TITLE
Looking for a special function

### ISSUE THREAD

**Issue by Supview** [georgepaterson/jquery-videobackground#43]
Hello George,

I'm using ascensor.js for a website, and i'm using your script for my video on each section.
So when a user is on the section first for exemple, he launch the first video by item " play button " then on the end of the video, he's directly redirected on the next section.
So here's my code at the moment : 

```
        $(document).ready(function() {
            $('#bg2').prepend('<div class="video-background"></div>');
            $('.video-background').videobackground({
                videoSource: [['video/goback.mp4', 'video/mp4'],
                    ['video/goback.webm', 'video/webm']], 
                autoplay: true,
                loop: false,
                controlPosition: '#bg2',
                loadedCallback: function() {
                $(this).videobackground('mute');
                },
                loadedCallback: function() {
                    this.find('video').on('ended', function () {
                        window.location.href = 'index.html#/choose1';
                        });
                        }
            });
        });
```

I would like to, when the video is finished, we are on the next section, but the video is also playing when we are on the right section. Is it possible instead to click always on the play buttom ?!

Thanks in advance,

**Comment by georgepaterson** [comment]
Not sure i understand but you can trigger a video to play with the play method:

this.videobackground('play')

It will trigger a play event without the need to click a play button. Was that what you needed?

**Comment by Supview** [comment]
Thanks for the answer,
I already tryied this, but the problem is that all the video are in one page but i different section.
I have create a custom button wich this one is in another section and would like to assign to this button the function of play button on it.
Like another controlposition, is it possible ?

**Comment by georgepaterson** [comment]
It's possible within the loadedCallback to set any element to trigger a video method. So you could have:

var that = $(this);
$('#test').on('click', function(event){
that.videobackground('play');
});
