### ISSUE TITLE
Creating a random loop of videos using a full-screen video background 

### ISSUE THREAD

**Issue by rabelais** [georgepaterson/jquery-videobackground#44]
Hi George,
We are looking into the possibility of creating a random or real-time loop of videos using a full-screen video background on an HTML site.
By 'random loop of videos' I mean that each user would find themselves at different stages of a video each time they log in.
By 'real-time loop of videos' I mean that the videos might be linked to play in real-time similar to movies at a cinema. 
Can this be done within your plug-in?
All the best,
Angela

**Comment by georgepaterson** [comment]
It sounds like a good idea but out of the box the plugin doesn't have the features you're looking for. I've kept it simply so people can extend it.
