### ISSUE TITLE
Switch between videos?

### ISSUE THREAD

**Issue by BlzDgtl** [georgepaterson/jquery-videobackground#48]
My client is wanting to have two different BG videos. One for the main website and one for a specific page within the site. When you click on the link to that single page, the first video would disappear and the other would take its place. 

What would be the easiest way to accomplish this?

**Comment by georgepaterson** [comment]
Are you loading the pages through page refresh or AJAX?

**Comment by BlzDgtl** [comment]
Sorry, I should have clarified that. The site is using AJAX so that the video continually plays in the background. I assume that I would need to switch the source or destroy one version and start a new one. The issue is that I need to be able to also switch back to the original version on the rest of the pages. 

Thanks for any guidance!

**Comment by georgepaterson** [comment]
Yeah, i haven't tried it but destroying the video and creating a new one may be the way to go so you get a new source.

**Comment by BlzDgtl** [comment]
This seemed to work. I set one button to destroy the main video and start a new one. I had to set up all other buttons to do the opposite. It worked out well.

**Comment by chaoos2** [comment]
It will be built into the code? I would need it. I also need to use more videos.
