### ISSUE TITLE
video loop

### ISSUE THREAD

**Issue by ghost** [georgepaterson/jquery-videobackground#49]
right now the video only loops a certain number of times.  how can i make it loop infinitely?

**Comment by georgepaterson** [comment]
There shouldn't be a finite number of loops, the loop attribute is infinite. Perhaps there's something else failing after a finite number of loops?

**Comment by ghost** [comment]
what you think i should look at?

**Comment by georgepaterson** [comment]
If you had a URL to look at i might be able to have a look.
