### ISSUE TITLE
Not working in IE9?

### ISSUE THREAD

**Issue by MindSculpt** [georgepaterson/jquery-videobackground#5]
Although HTML5 video is supported in IE 9, it appears your script displays the static image. Was this an oversight, or is there a way to also support IE9+?

**Comment by georgepaterson** [comment]
The plugin works with IE9 but if the browser is running in IE7/IE8 or compatibility modes it will not render the video element. As such it will revert to using a poster if provided.

Try switching the browser and document mode in the developer tools in IE9 on http://html5demos.com/video as an independent example.
