### ISSUE TITLE
Video not playing on safari?

### ISSUE THREAD

**Issue by rabelais** [georgepaterson/jquery-videobackground#50]
Hi, 

Thank you for you plugin.

My video is not playing in the safari browser. It works locally on my safari browser. Is it something to do with my server settings?  Could you please advise me how to fix this. http://www.flatness.eu/gil-leung-video.html

Thanks.

**Comment by georgepaterson** [comment]
The .mp4 doesn't seem to load or play in browser so could be an issue with the video.

**Comment by georgepaterson** [comment]
Either it could be related to issue #42 or try the resolution from issue #34
