### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Howman** [georgepaterson/jquery-videobackground#54]
O.k. I got Windows 8.1 and IE 11 and your plugin is now working on my site but is not working on your demo site. (not my question just wanted to let you know that everything is all good now)

I do not know if your busy or not and there really is no rush but I asked about a year ago on (August 6, 2012 at 12:17 am).
Could the ability to add more then one video and maybe even random pay a list of like 3 or 4 different videos.
So is there a possibility this could still be done?

**Comment by georgepaterson** [comment]
Cool thanks Howman.

The play list is something i'd like to do but i just don't find the time between work and fatherhood. Sorry.

**Comment by Howman** [comment]
georgepaterson Hello it just me again asking if you have any time to add the ability to play more then one video It's been another year and just wondering if you have time to update/make changes to your plugin.
