### ISSUE TITLE
iPad Solution

### ISSUE THREAD

**Issue by BlzDgtl** [georgepaterson/jquery-videobackground#55]
I know that Apple has changed the parameters for iOS devices, not allowing autoplay for background video on iPad. Has anyone found a solution to trigger it once the site has in fact loaded. Do you have any recommendations for the trigger to start the playing? I really need to find a hack around this... any ideas?

Thanks :)

**Comment by georgepaterson** [comment]
The plugin has a play method, the same method used on the play button by default. So what you can do is perhaps test you're on an iOS device and trigger the play method when the DOM is ready, or you could remove autoplay entirely and trigger the play method for all browsers.

**Comment by BlzDgtl** [comment]
Would you be able to provide a sample of how you might go about this? I've tried a handful of tests and have had no luck. I've turned off autoplay and tried probably 10 different  method of triggering the play - everything from delayed timeouts and waiting for an image to load. No luck. Any help would be AWESOME!

**Comment by PsykOlivier** [comment]
Hi,
Did you find a solution ?

**Comment by georgepaterson** [comment]
You could either call the the plugin method directly or perhaps use the jQuery trigger method on the play button http://api.jquery.com/trigger/

Not sure if it'll work, i do remember Apple trying to remove all automated methods of playing a video for iOS to save battery and bandwidth for the user.
