### ISSUE TITLE
DivX-Webplayer-Plugin always takes over

### ISSUE THREAD

**Issue by lucowehrlin** [georgepaterson/jquery-videobackground#58]
When opening the website with a browser that has the DivX-Webplayer-Plugin installed, that one always takes over the video-playback. Issue with that is, that it somehow doesn't display the video in the correct ratio (I always end up with a black border, at least on the left side), muting the video doesn't work and the controls aren't visible as it would be with normal WebM-Video.

That behaviour doesn't happen when developing/testing locally, only when I have uploaded the site to it's destination and test it from there.

Any hint on how to avoid that?

**Comment by georgepaterson** [comment]
Have you checked that the file is being served properly? Try the resolution from issue #34
