### ISSUE TITLE
How to pattern PNG file on the video ?

### ISSUE THREAD

**Issue by mohsen123** [georgepaterson/jquery-videobackground#59]
Hi there.

I just like to know is it possible to load and pattern a transparent png file on the video ?
I mean something like : 
http://themes.renklibeyaz.com/?theme=ThisWayWP
please see "Dark" site and let the "EMILY DIDONATO" video play, You'll see some little Black Dots patterned on the video, or something like : 
http://www.kriesi.at/themedemo/?theme=flashlight
done on the fullscreen background image with thin lines!

many thanks

**Comment by georgepaterson** [comment]
Not really in the scope of the plugin but you could have a transparent png layered on top of the video.
