### ISSUE TITLE
SWF fallback

### ISSUE THREAD

**Issue by ic3y** [georgepaterson/jquery-videobackground#6]
Hi,

Is there an option to fall back on SWF? I like this plugin a lot, but i'd like to give Iexplorer 7 and 8 users (still a large part of my visitors) also the option to view the video.

Thank you in advance.

**Comment by georgepaterson** [comment]
I had though about supporting IE7 & 8 using https://github.com/georgepaterson/simple_video_player but i do have concerns about the benefit and the performance issues with older browsers. Clients that have used the plugin have found a lack of IE7 & 8 support acceptable. So at the moment it's not something I'm supporting.
