### ISSUE TITLE
Video after loop, unmutes itself?

### ISSUE THREAD

**Issue by nickngqs** [georgepaterson/jquery-videobackground#62]
Hi,

I noticed when the video finishes and began its first loop, it auto unmutes itself. Is this a bug or can I solve this?

**Comment by cdanea** [comment]
I get this too.

**Comment by ewtstudio** [comment]
Hi,
I have the same problem.
How can I solve this issue?
Thank you very much..

**Comment by cdanea** [comment]
I just gave up and used raw css and javascript to place the native player in z-index:-1

**Comment by ewtstudio** [comment]
Thank you very much Cdanea,
I'll try it.
Regards..
