### ISSUE TITLE
Video not resize in Safari

### ISSUE THREAD

**Issue by Akrosid** [georgepaterson/jquery-videobackground#63]
On firefox as I change the window size to fit the video. But on safari it is trimmed. How?

**Comment by georgepaterson** [comment]
Sorry i don't know what the problem is, do you have an example?

**Comment by baronmunchowsen** [comment]
I can reproduce this issue. The attached screenshots might help. 
OSX 10.8.5
Safari Version 6.1.1

On load - the background video kicks in as it should

![1 on-load](https://f.cloud.github.com/assets/280883/2047296/6dab3d8a-8a19-11e3-9ae1-eddd50586c71.jpg)

Upon resize - the background video does not fill out the background of the browser window (depending on the width/height to which it is resized)

![2 post-resize](https://f.cloud.github.com/assets/280883/2047295/6d8ebcfa-8a19-11e3-96f9-7b537ac4e94f.jpg)

Upon refresh - the background video does fill out the background as expected.

![3 post-resize-post-refresh](https://f.cloud.github.com/assets/280883/2047297/6dbe920e-8a19-11e3-847f-d33a0433973a.jpg)

Hope this helps!

**Comment by georgepaterson** [comment]
I see it, that is tricky. Firefox doesn't have the same problem as a comparison, it looks like it's something to do with how the aspect ratio for the video is calculated by Chrome. Will have to investigate.

**Comment by georgepaterson** [comment]
On paternity leave at the moment, try the comment in issue #71
