### ISSUE TITLE
Play event - to play only (not also pause the video)

### ISSUE THREAD

**Issue by Pixelalb** [georgepaterson/jquery-videobackground#65]
And here's a particular case. 

I am firing the play event on window scroll, when an element becomes visible in the viewport. 
On scroll the video plays and pauses. 

Is there a way to make play event only play the movie?

**Comment by georgepaterson** [comment]
You can call the play method directly .videobackground('play'), it is separate to the pause method, so i'm not sure why it pauses as that's not part of the plugin.
