### ISSUE TITLE
horizontall slide

### ISSUE THREAD

**Issue by imranasim** [georgepaterson/jquery-videobackground#66]
hey, i want to ask if this is possible, am using horizontal scroll on my website to show the pages, basically there are 5 pages and am using video on background only on 1st page means on 1st slide, so if i slide next i want the audio to mute..is it possible?

In simple words, when i slide the pages, the audio still remains ON which distract users.. any solutions?

**Comment by AWPhilArena** [comment]
Subject: [jquery-videobackground] horizontall slide (#66)

hey, i want to ask if this is possible, am using horizontal scroll on my website to show the pages, basically there are 5 pages and am using video on background only on 1st page means on 1st slide, so if i slide next i want the audio to mute..is it possible?

In simple words, when i slide the pages, the audio still remains ON which distract users.. any solutions?

/*
     \* Mute function.
     \* Can either be called through the default control interface or directly through the public method.
     \* Will set the video to mute or unmute depending on existing state.
     \* Requires the video to be loaded.
     *
     */

Taken from jquery.videobackground.js

**Comment by georgepaterson** [comment]
Yeah that's it you can call the mute function directly and bind it to any event .videobackground('mute');

**Comment by imranasim** [comment]
Thanks alot, can you please show me any example of this code?

**Comment by georgepaterson** [comment]
They're available in the tests folder.
