### ISSUE TITLE
Replace Control Icons

### ISSUE THREAD

**Issue by pahnl** [georgepaterson/jquery-videobackground#67]
Hello,

I want to replace the jquery icons with font icons from Font Awesome but I'm just not familiar with jquery whatsoever. I had a dig around the files and I spent a lot of today trying to make it work via trial and error but with limited success.

I was able to make a pause icon appear by fiddling with the following code in jquery.videobackground.js, which acts how I would like but then the controls disappear:

```
                    that.controls = $('<ul class="ui-video-background-controls"><li class="ui-video-background-play">'
                        + '<a class="ui-icon ui-icon-pause" href="#">' + that.settings.controlText[1] + '</a>'
                        + '</li><li class="ui-video-background-mute">'
                        + '<a class="ui-icon ui-icon-volume-on" href="#">' + that.settings.controlText[2] + '</a>'
                        + '</li></ul>');
```

Any help would be greatly appreciated as, apart from relatively simple html and css, I'm stumbling in the mist.

Also, when I specify a poster image in the page's script, Chrome will not autoplay the video without scrolling down the page or hovering over a link.

And lastly, as if posing all these ignorant questions to someone who isn't being paid for supporting their free code was bad enough, is there any code hanging around that would force iOS to skip the video background and display the poster right away, as otherwise a large 'play' icon appears, which when clicked, leads the user to a separate video player.

Sorry, thank you, sorry. Sorry.

**Comment by georgepaterson** [comment]
Sorry about the delay. 

Don't try editing jquery.videobackground, you can hide the controls with CSS and use your own controls. If you do want to use the controls as defined, you can also update them with CSS, you're not restricted to the default look and feel.

iOS really doesn't like auto play video, it needs a user action to initiate, maybe it could be triggered on a touch interaction. Looks like the same problem with Chrome.
