### ISSUE TITLE
Safari Resize Issue

### ISSUE THREAD

**Issue by baronmunchowsen** [georgepaterson/jquery-videobackground#71]
Thanks for a great plugin.

Not sure whether I should be opening a new issue, or updating one that is closed (so I have done both).

With
OSX 10.8.5
Safari Version 6.1.1

The video does not fill the background upon browser resize. See other issue for screenshots.

Duplicate of: https://github.com/georgepaterson/jquery-videobackground/issues/63#issuecomment-33755113

**Comment by SourceCodeplz** [comment]
Maybe we can set a video resize function on the onWindowResize action?

**Comment by georgepaterson** [comment]
Triggering the public resize method onWindowResize sounds like a good starting point.
