### ISSUE TITLE
Whole page in Internet Explorer is blank unless you press on it or explore the DOM with dev tools

### ISSUE THREAD

**Issue by karooolis** [georgepaterson/jquery-videobackground#72]
Hi there,

First of all, I would like to say thank you George, great plugin! It works across all major browsers and I have nothing bad to say. However, I am experiencing issues with Internet Explorer ( as always... ) and my whole website looks absolutely white unless you click on it several times or use developer tools to select something from DOM. Then somehow it appears out of nowhere. Do you know what the issue could be? The site is http://zerobrainwash.com/sandbox/buzzing/index.html .

Cheers in advance, Karolis :)

**Comment by georgepaterson** [comment]
Looks like you've gone for videoBG, fair play.

**Comment by karooolis** [comment]
That is true since I did not manage to solve the problem myself and the project needed to be done. Sorry about that and thank you for taking time to have a look.

**Comment by georgepaterson** [comment]
No worries, been on paternity leave so haven't had much time for coding.

**Comment by karooolis** [comment]
Good luck ;)
