### ISSUE TITLE
Element BG with text over

### ISSUE THREAD

**Issue by CECAaron** [georgepaterson/jquery-videobackground#77]
George, 

I've set the video to be a background of an DIV element, which has some text in it. I cannot seem to make the background sit below the text with the text above it. 

Here is the CSS:

/\* the container the video is being inserted into _/
.vid_header{
     height:550px;
     text-align:center;
     overflow:hidden;
}
/_ the text that should be above the video */
.vid_header h1{
    text-align:center;
    line-height:500px;
    font-family: "Trebuchet MS", Verdana, sans-serif;
    font-weight:bold;
    font-size:100px;
    color:#FFF; 
    text-shadow:2px 2px 20px rgba(0,0,0,0.5);
    z-index:999;
    position:realtive;
}

.video-background {
    position: relative;
    top: 0;
    left: 0;
    overflow: hidden;
    width: 100%;
    z-index: -5 !important;
}
.video-background video {
    min-width:100%;
    position: relative;
}

Here is the jQuery (using Wordpress PHP for the file paths):

$('.vid_header').prepend('<div class="video-background"></div>');
    $('.video-background').videobackground({
        videoSource: [['<?php bloginfo('template_directory');?>/videos/background.mp4', 'video/mp4'],
            ['<?php bloginfo('template_directory');?>/videos/background.webm', 'video/webm'], 
            ['video/<?php bloginfo('template_directory');?>/videos/background.ogv', 'video/ogg']], 
        controlPosition: '#main',
        loop:true,
        poster: '<?php bloginfo('template_directory');?>/images/bg_logo.jpg',
        loadedCallback: function() {
            $(this).videobackground('mute');
        }
    });

What am I missing?

**Comment by georgepaterson** [comment]
The video element will always rise to the surface. You need a sibling element in the DOM that the text can then be placed above the video element.

See: http://georgepaterson.github.io/jquery-videobackground/ 

The div id="page" is the sibling element with a relative position allowing the text to sit above the video element that is contained in div class="video-background"

**Comment by CECAaron** [comment]
Thank you! It seemed that in addition to your suggestion, I needed to change the position of the ".video-background" from relative to absolute. The combination of those two changes fixed the problem.
