### ISSUE TITLE
the code did not work

### ISSUE THREAD

**Issue by VietDucPhan** [georgepaterson/jquery-videobackground#8]
hi, after download your code and upload it on my sever to test it, i find that it would not play at all. i check it on firefox, and on chrome only a small movie window play on the left top. would you show me what need to be done so that the code could work?

http://vietthietkeweb.net/1111/

Thanks in advanced

**Comment by georgepaterson** [comment]
Seems to be working for me on your site in Chrome. I suggest it's not the fault of the plugin but you need to make sure the config of the videos and Apache is correct on the site and that isn't something i can help you with. Sorry Viet.
