### ISSUE TITLE
Updated to Chrome 35.0.1916.114 and video no longer plays

### ISSUE THREAD

**Issue by eljacobs** [georgepaterson/jquery-videobackground#80]
I just updated Chrome to 35.0.1916.114

The plugin works (i.e. the inspector shows the video-background div being added and the poster image is there) but the video doesn't play. 

The video does play in firefox and safari.

**Comment by georgepaterson** [comment]
See issue #79, looks like the Chrome release changed the default action of preload="none". Will be updating the project later this week.

**Comment by eljacobs** [comment]
many thanks for the quick response (and the great plugin!)

**Comment by georgepaterson** [comment]
Default setting changed in tag 1.4.1.

**Comment by JXH2014** [comment]
Yep, got the same issue here.
