### ISSUE TITLE
video not working in windows safari.

### ISSUE THREAD

**Issue by ghost** [georgepaterson/jquery-videobackground#83]
Background Video not working in windows safari, while working fine with rest of all the browsers.
Please Help.

**Comment by georgepaterson** [comment]
I've just successfully tested http://georgepaterson.github.io/jquery-videobackground/ on Safari 7.05

You'll need to provide more information for me to investigate.

**Comment by ghost** [comment]
I tested your link, and its same issue. Please check the screenshot below -
http://awesomescreenshot.com/0b436wiib0

I m checking it in windows safari version 5.1.5

**Comment by georgepaterson** [comment]
Video is not natively supported in Windows Safari and requires Quicktime. Apple dropped support for Windows Safari, so developing for it is at risk.
