### ISSUE TITLE
Always stretch to window height

### ISSUE THREAD

**Issue by ursbraem** [georgepaterson/jquery-videobackground#9]
Hi George

Thanks for this!

I'd rather have the background adapt seamlessly to the window height. If you have a page with a lot of scrollable text (which is the normal case nowadays), you will expect the background to stay fixed and be able to scroll the stuff in front of that. Cf. your own demo page.

I have made the following changes:
.video-background {
        position: fixed;
}

function resize (element) {
        var documentHeight = $(document).height(),
            windowHeight = $(window).height();
        //if (windowHeight >= documentHeight) {
            $(element).css('height', windowHeight);
        //}
        //else if (documentHeight > windowHeight) {
        //  $(element).css('height', documentHeight);
        //  }
}

... maybe this could be included as an option "resizeTo" (window, document)?

Best regards
Urs

**Comment by georgepaterson** [comment]
Looks like i need to put an additional option in to allow this as part of the plugin options. Shouldn't be too tricky.

**Comment by solalgaillard** [comment]
Hi George,

I'd like to second ursbraem on that one. It would really be great. I feel that's the only thing missing to that great plugin.

Cheers,

Solal

**Comment by georgepaterson** [comment]
Update checked in with resizeTo option.

**Comment by ursbraem** [comment]
Nice
